name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  release-assets:
    name: Publish release assets for ${{ matrix.arch }}
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [linux, windows, darwin]
        include:
          - arch: linux
            os: ubuntu-latest

          - arch: windows
            os: ubuntu-latest

          - arch: darwin
            os: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - run: make release/aggspread-${{ matrix.arch }}-amd64.tar.gz

      - name: Upload assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: release/aggspread-${{ matrix.arch }}-amd64.tar.gz
          asset_name: aggspread-${{ matrix.arch }}-amd64.tar.gz
          asset_content_type: application/gzip
